# Generated by Django 3.0.5 on 2020-04-17 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliding_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('home_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
